Repository connium/simple-odf, pull requests merged in 2019-10, with the labels that each got.

#120 text content of a list item cannot be styled
  CHANGELOG.md
  README.md
  examples/homer-resume/index.ts
  src/api/office/TextBody.ts
  src/api/text/List.spec.ts
  src/api/text/List.ts
  src/api/text/ListItem.spec.ts
  src/api/text/ListItem.ts
  src/xml/DomVisitor.spec.ts
  test/integration.spec.ts
Labels: Hacktoberfest

#121 implement sublists
  CHANGELOG.md
  src/api/text/ListItem.spec.ts
  src/api/text/ListItem.ts
  test/integration.spec.ts
Labels: Hacktoberfest, enhancement

#123 chore(lint): replace tslint with eslint (#122)
  .eslintrc.json
  CHANGELOG.md
  package-lock.json
  package.json
  tslint.json
Labels: Hacktoberfest, dependencies

#125 use standardx for linting, fix linting errors, remove tslint annotations
  .eslintrc.json
  .npmignore
  CHANGELOG.md
  examples/homer-resume/index.ts
  package-lock.json
  package.json
  src/api/meta/Meta.ts
  src/api/office/AutomaticStyles.spec.ts
  src/api/office/AutomaticStyles.ts
  src/api/style/FontFace.ts
  src/api/style/ParagraphProperties.ts
  src/api/style/ParagraphStyle.ts
  src/api/style/Style.ts
  src/api/style/TabStop.spec.ts
  src/api/text/Hyperlink.ts
  src/xml/DomVisitor.spec.ts
  src/xml/OdfTextElementWriter.ts
  src/xml/meta/MetaWriter.spec.ts
  src/xml/office/FontFaceDeclarationsWriter.spec.ts
  src/xml/office/StylesWriter.spec.ts
  src/xml/office/StylesWriter.ts
  test/integration.spec.ts
Labels: dependencies

#126 chore(deps-dev): update handlebars dependencies
  package-lock.json
Labels: dependencies
